<#
    FinanceHubProvisioner.ps1
    Version-safe, idempotent provisioning of a Finance / Ledger / Quotes Hub in SharePoint Online.

    Includes:
      - Entra App + cert auth for PnP (no PFX password stored in INI)
      - Team site creation / reuse
      - Regional settings (Locale, Time zone, first day, 24h clock) with CSOM fallback
      - Base currency prompt → CurrencyLocaleId applied to all Currency fields
      - Lists: Customers, Suppliers, Ledger; Libraries: Invoices, Receipts
      - NEW: Quotes (with docs library, linking, conversion to invoice)
      - Customer/Supplier Codes (auto-generated by your app/API)
      - Customers: Billing Address, Day Rate, Hourly Rate, VAT Registered flag
      - VAT fields (VATApplicability, VATIncluded default Yes, VATRate default 20)
      - Discount fields on Invoices and Quotes (Percent, Amount, Note)
      - Customer PO/Ref, Paid/DatePaid, DLA, RelatedDocument, Notes
      - Company Settings list (seeded "Default" profile) for identity & FY boundary
      - Ledger NeedsCalc (default Yes) to drive Flow calculations
      - Views: Ledger Income / Expenses / Unpaid Invoices; Invoices; Receipts; Quotes
      - Lookup creation via Add-PnPFieldFromXml (works on PnP v3.x incl. 3.1.0)

    Persists config: finance-hub-config.ini
#>

param(
    [switch]$ForceRecreateApp
)

$ErrorActionPreference = "Stop"
$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$configFile = Join-Path $scriptRoot "finance-hub-config.ini"

# ===========================
# INI HELPERS (defensive)
# ===========================
function Get-IniContent {
    param([string]$Path)
    $ini = @{}
    if (-not (Test-Path $Path)) { return $ini }
    $section = $null
    switch -regex -file $Path {
        '^\s*\[(.+)\]\s*$' {
            $section = $matches[1]
            if (-not $ini.ContainsKey($section)) { $ini[$section] = @{} }
        }
        '^\s*([^=]+?)\s*=\s*(.*)$' {
            if (-not $section) { $section = "Default"; if (-not $ini.ContainsKey($section)) { $ini[$section] = @{} } }
            $name = $matches[1].Trim()
            $value = $matches[2]
            $ini[$section][$name] = $value
        }
    }
    return $ini
}

function Set-IniValue {
    param([string]$Path,[string]$Section,[string]$Key,[string]$Value)
    if (-not (Test-Path $Path)) { "# FinanceHub Configuration" | Set-Content -Path $Path -Encoding UTF8 }
    $ini = Get-IniContent -Path $Path
    if (-not $ini.ContainsKey($Section)) { $ini[$Section] = @{} }
    $ini[$Section][$Key] = $Value
    $sb = New-Object System.Text.StringBuilder
    foreach ($sec in $ini.Keys) {
        [void]$sb.AppendLine("[$sec]")
        foreach ($k in $ini[$sec].Keys) { [void]$sb.AppendLine("$k=$($ini[$sec][$k])") }
        [void]$sb.AppendLine("")
    }
    $sb.ToString() | Set-Content -Path $Path -Encoding UTF8
}

function Get-IniValueOrPrompt {
    param(
        [string]$Path,[string]$Section,[string]$Key,
        [string]$Prompt,[string]$Default = "",
        [switch]$AllowBlank
    )
    if (-not (Test-Path $Path)) { "# FinanceHub Configuration" | Set-Content -Path $Path -Encoding UTF8 }
    $ini = Get-IniContent -Path $Path
    if (-not $ini.ContainsKey($Section)) { $ini[$Section] = @{} }

    $value = $null
    if ($ini[$Section].ContainsKey($Key)) { $value = $ini[$Section][$Key] }

    if ([string]::IsNullOrWhiteSpace($value)) {
        if ([string]::IsNullOrWhiteSpace($Default)) {
            $value = Read-Host $Prompt
        } else {
            $input = Read-Host "$Prompt [$Default]"
            $value = if ([string]::IsNullOrWhiteSpace($input)) { $Default } else { $input }
        }

        if (-not $AllowBlank) {
            while ([string]::IsNullOrWhiteSpace($value)) {
                $value = Read-Host $Prompt
            }
        }
        Set-IniValue -Path $Path -Section $Section -Key $Key -Value $value
    }
    return $value
}

# ===========================
# UTILITY HELPERS
# ===========================
function Ensure-Module {
    param([string]$Name,[string]$MinVersion="0.0.0")
    $installed = Get-Module -ListAvailable -Name $Name | Where-Object { $_.Version -ge [version]$MinVersion } | Select-Object -First 1
    if (-not $installed) {
        Write-Host "Installing $Name (min $MinVersion)..." -ForegroundColor Yellow
        Install-Module -Name $Name -MinimumVersion $MinVersion -Scope CurrentUser -Force -AllowClobber
    } else {
        Write-Host "✓ $Name v$($installed.Version) already installed" -ForegroundColor Green
    }
}

function Ensure-List {
    param([string]$Title,[string]$Template="GenericList",[bool]$EnableAttachments=$true,[string]$Url=$null,[switch]$OnQuickLaunch)
    $l = Get-PnPList -Identity $Title -ErrorAction SilentlyContinue
    if (-not $l) {
        Write-Host "Creating list/library: $Title" -ForegroundColor Yellow
        if ([string]::IsNullOrWhiteSpace($Url)) { $Url = ($Title -replace '\s+','-') }
        $params = @{ Title=$Title; Template=$Template; Url=$Url }
        if ($OnQuickLaunch) { $params["OnQuickLaunch"] = $true }
        New-PnPList @params | Out-Null
        if ($Template -eq "GenericList") { Set-PnPList -Identity $Title -EnableAttachments:$EnableAttachments | Out-Null }
    } else { 
        Write-Host "✓ Exists: $Title" -ForegroundColor Green 
        # Ensure attachments setting is correct for existing lists
        if ($Template -eq "GenericList") { 
            Set-PnPList -Identity $Title -EnableAttachments:$EnableAttachments | Out-Null 
        }
    }
}

# --- Version-safe lookup creation using Add-PnPFieldFromXml ---
function Ensure-LookupField {
    param(
        [string]$ListTitle,[string]$DisplayName,[string]$InternalName,
        [string]$LookupListTitle,[string]$LookupField = "Title",
        [bool]$Required = $false,[bool]$AddToDefaultView = $true
    )
    $existing = Get-PnPField -List $ListTitle -Identity $InternalName -ErrorAction SilentlyContinue
    if ($existing) { return }

    $target = Get-PnPList -Identity $LookupListTitle -ErrorAction Stop
    $listGuid = $target.Id.Guid
    $req = if ($Required) { "TRUE" } else { "FALSE" }

    $xml = @"
<Field Type="Lookup"
       DisplayName="$DisplayName"
       StaticName="$InternalName"
       Name="$InternalName"
       List="{$listGuid}"
       ShowField="$LookupField"
       Required="$req" />
"@

    Add-PnPFieldFromXml -List $ListTitle -FieldXml $xml | Out-Null

    if ($AddToDefaultView) {
        $view = Get-PnPView -List $ListTitle -Identity "All Items" -ErrorAction SilentlyContinue
        if ($view) {
            $fields = @($view.ViewFields)
            if ($fields -notcontains $InternalName) {
                $fields += $InternalName
                Set-PnPView -List $ListTitle -Identity $view.Id -Fields $fields | Out-Null
            }
        }
    }
}

function Ensure-Field {
    param(
        [string]$List,[string]$DisplayName,[string]$InternalName,
        [ValidateSet("Text","Note","Number","Currency","DateTime","Choice","Boolean","URL","Lookup")]$Type,
        [string[]]$Choices = $null,
        [string]$LookupList = $null,
        [string]$LookupField = "Title",
        [bool]$Required=$false,
        [bool]$AddToDefaultView=$true,
        [bool]$EnforceUnique=$false,
        [bool]$Indexed=$false
    )
    $exists = Get-PnPField -List $List -Identity $InternalName -ErrorAction SilentlyContinue
    if (-not $exists) {
        if ($Type -eq "Choice" -and $Choices) {
            Add-PnPField -List $List -DisplayName $DisplayName -InternalName $InternalName -Type Choice -Choices $Choices -AddToDefaultView:$AddToDefaultView | Out-Null
        } elseif ($Type -eq "Lookup" -and $LookupList) {
            Ensure-LookupField -ListTitle $List -DisplayName $DisplayName -InternalName $InternalName -LookupListTitle $LookupList -LookupField $LookupField -Required:$Required -AddToDefaultView:$AddToDefaultView
        } else {
            Add-PnPField -List $List -DisplayName $DisplayName -InternalName $InternalName -Type $Type -AddToDefaultView:$AddToDefaultView | Out-Null
        }
    }
    if ($Indexed -or $EnforceUnique) { Set-PnPField -List $List -Identity $InternalName -Values @{ Indexed = $true } | Out-Null }
    if ($EnforceUnique) { Set-PnPField -List $List -Identity $InternalName -Values @{ EnforceUniqueValues = $true } | Out-Null }
    if ($Required) { Set-PnPField -List $List -Identity $InternalName -Values @{ Required = $true } | Out-Null }
}

function Ensure-View {
    param([string]$List,[string]$Title,[string[]]$Fields,[string]$Query=$null,[int]$RowLimit=50)
    $v = Get-PnPView -List $List -Identity $Title -ErrorAction SilentlyContinue
    if (-not $v) {
        Add-PnPView -List $List -Title $Title -Fields $Fields -RowLimit $RowLimit -Query $Query | Out-Null
        Write-Host "Created view: $Title (List: $List)" -ForegroundColor Yellow
    }
}

# ---- Currency helpers ----
function Get-CurrencyLocaleId {
    param([string]$Code)
    $map = @{
        "GBP" = 2057   # en-GB → £
        "USD" = 1033   # en-US → $
        "EUR" = 6153   # en-IE → €
        "AUD" = 3081   # en-AU → A$
        "CAD" = 4105   # en-CA → C$
        "NZD" = 5129   # en-NZ → NZ$
        "ZAR" = 7177   # en-ZA → R
        "SEK" = 1053   # sv-SE → kr
        "NOK" = 1044   # nb-NO → kr
        "DKK" = 1030   # da-DK → kr
        "CHF" = 2055   # de-CH → CHF
        "JPY" = 1041   # ja-JP → ¥
    }
    $code = $Code.ToUpperInvariant()
    if ($map.ContainsKey($code)) { return $map[$code] }
    return 2057  # default to en-GB if unknown
}

function Set-CurrencyOnField {
    param([string]$List,[string]$FieldInternalName,[int]$CurrencyLcid)
    try {
        Set-PnPField -List $List -Identity $FieldInternalName -Values @{ CurrencyLocaleId = $CurrencyLcid } | Out-Null
    } catch {
        Write-Warning ("Could not set currency on {0}/{1}: {2}" -f $List, $FieldInternalName, $_.Exception.Message)
    }
}

# ---- Regional settings fallback (if Set-PnPRegionalSettings not available) ----
function Convert-FirstDayToEnum {
    param([string]$FirstDay)
    switch ($FirstDay.ToLower()) {
        "monday"    { return 1 }
        "tuesday"   { return 2 }
        "wednesday" { return 3 }
        "thursday"  { return 4 }
        "friday"    { return 5 }
        "saturday"  { return 6 }
        default     { return 0 } # Sunday
    }
}

function Apply-RegionalSettings {
    param(
        [int]$LocaleId,
        [string]$TimeZoneName = "GMT Standard Time",
        [string]$FirstDayOfWeek = "Monday",
        [bool]$Use24HourClock = $true
    )

    $cmd = Get-Command -Name Set-PnPRegionalSettings -ErrorAction SilentlyContinue
    if ($cmd) {
        try {
            $zones = Get-PnPTimeZoneId
            $tz = $zones | Where-Object { $_.Description -eq $TimeZoneName -or $_.Id -eq $TimeZoneName } | Select-Object -First 1
            if (-not $tz) {
                $tz = $zones | Where-Object { $_.Description -eq "GMT Standard Time" } | Select-Object -First 1
                Write-Warning "Time zone '$TimeZoneName' not found, falling back to 'GMT Standard Time'."
            }
            Set-PnPRegionalSettings -LocaleId $LocaleId -TimeZone $tz.Id -FirstDayOfWeek $FirstDayOfWeek -Time24 $Use24HourClock | Out-Null
            Write-Host "✓ Regional settings applied via Set-PnPRegionalSettings" -ForegroundColor Green
            return
        } catch {
            Write-Warning ("Set-PnPRegionalSettings failed, using CSOM fallback: {0}" -f $_.Exception.Message)
        }
    }

    # CSOM fallback
    try {
        $ctx = Get-PnPContext
        $web = Get-PnPWeb
        $ctx.Load($web.RegionalSettings)
        $ctx.ExecuteQuery()

        $zones = Get-PnPTimeZoneId
        $tzObj = $zones | Where-Object { $_.Description -eq $TimeZoneName -or $_.Id -eq $TimeZoneName } | Select-Object -First 1
        if (-not $tzObj) {
            $tzObj = $zones | Where-Object { $_.Description -eq "GMT Standard Time" } | Select-Object -First 1
            Write-Warning "Time zone '$TimeZoneName' not found, falling back to 'GMT Standard Time'."
        }

        $tz = $web.RegionalSettings.TimeZones.GetById([int]$tzObj.Id)
        $ctx.Load($tz)
        $ctx.ExecuteQuery()

        $web.RegionalSettings.LocaleId = [int]$LocaleId
        $web.RegionalSettings.TimeZone = $tz
        $web.RegionalSettings.FirstDayOfWeek = Convert-FirstDayToEnum -FirstDay $FirstDayOfWeek
        $web.RegionalSettings.Time24 = [bool]$Use24HourClock
        $web.Update()
        $ctx.ExecuteQuery()

        Write-Host "✓ Regional settings applied via CSOM fallback" -ForegroundColor Green
    } catch {
        Write-Warning ("Could not set regional settings: {0}" -f $_.Exception.Message)
    }
}

# ===========================
# MAIN
# ===========================
try {
    if (-not (Test-Path $configFile)) { "# FinanceHub Configuration" | Set-Content $configFile -Encoding UTF8 }

    Ensure-Module -Name "PnP.PowerShell" -MinVersion "2.0.0"
    Import-Module PnP.PowerShell -ErrorAction Stop

    # Tenant & branding
    $tenantShort = Get-IniValueOrPrompt -Path $configFile -Section "Tenant" -Key "ShortName" -Prompt "Tenant short name (e.g. kempy)"
    $tenantId = "$tenantShort.onmicrosoft.com"
    $rootUrl  = "https://$tenantShort.sharepoint.com"
    $adminUrl = "https://$tenantShort-admin.sharepoint.com"
    Set-IniValue -Path $configFile -Section "Tenant" -Key "TenantId" -Value $tenantId
    Set-IniValue -Path $configFile -Section "Tenant" -Key "RootUrl" -Value $rootUrl
    Set-IniValue -Path $configFile -Section "Tenant" -Key "AdminUrl" -Value $adminUrl

    $company = Get-IniValueOrPrompt -Path $configFile -Section "Brand" -Key "CompanyDisplay" -Prompt "Company initials (e.g. AK)" -Default "AK"
    $product = Get-IniValueOrPrompt -Path $configFile -Section "Brand" -Key "Product" -Prompt "Hub type (LedgerHub or FinanceHub)" -Default "LedgerHub"
    if ($product -notin @("LedgerHub","FinanceHub")) { $product = "LedgerHub"; Set-IniValue -Path $configFile -Section "Brand" -Key "Product" -Value $product }

    $siteTitleDefault = "$company $product"
    $siteTitle = Get-IniValueOrPrompt -Path $configFile -Section "SharePoint" -Key "SiteTitle" -Prompt "SharePoint site title" -Default $siteTitleDefault
    $aliasDefault = (($company + $product) -replace '\s+','').ToLowerInvariant()
    $siteAlias = Get-IniValueOrPrompt -Path $configFile -Section "SharePoint" -Key "SiteAlias" -Prompt "Site URL name, /sites/<name>" -Default $aliasDefault
    $siteUrl = "$rootUrl/sites/$siteAlias"
    Set-IniValue -Path $configFile -Section "SharePoint" -Key "SiteUrl" -Value $siteUrl

    $ownerUpn = Get-IniValueOrPrompt -Path $configFile -Section "SharePoint" -Key "OwnerUpn" -Prompt "Site Owner UPN (needed if the site must be created)" -AllowBlank

    # Regional settings (UK defaults; configurable)
    $localeIdStr = Get-IniValueOrPrompt -Path $configFile -Section "Regional" -Key "LocaleId" -Prompt "LocaleId (2057=en-GB, 1033=en-US, etc.)" -Default "2057"
    [int]$localeId = $localeIdStr
    Set-IniValue -Path $configFile -Section "Regional" -Key "LocaleId" -Value "$localeId"

    $timeZoneName = Get-IniValueOrPrompt -Path $configFile -Section "Regional" -Key "TimeZone" -Prompt "Time zone display name" -Default "GMT Standard Time"
    Set-IniValue -Path $configFile -Section "Regional" -Key "TimeZone" -Value $timeZoneName

    $firstDay = Get-IniValueOrPrompt -Path $configFile -Section "Regional" -Key "FirstDayOfWeek" -Prompt "First day of week (Sunday/Monday/...)" -Default "Monday"
    $use24h = Get-IniValueOrPrompt -Path $configFile -Section "Regional" -Key "Use24HourClock" -Prompt "Use 24-hour clock? (Y/N)" -Default "Y"
    $use24hBool = ($use24h.ToUpperInvariant() -eq "Y")

    # Base currency prompt
    $baseCurrencyCode = Get-IniValueOrPrompt -Path $configFile -Section "Finance" -Key "BaseCurrency" -Prompt "Base currency code (GBP, USD, EUR, ...)" -Default "GBP"
    $currencyLcid = Get-CurrencyLocaleId -Code $baseCurrencyCode
    Set-IniValue -Path $configFile -Section "Finance" -Key "CurrencyLCID" -Value "$currencyLcid"

    # Discounts toggle (always enabled for invoices and quotes now)
    $enableDiscounts = $true

    # App registration
    $appNameDefault = "$company-$product-PnP"
    $appName = Get-IniValueOrPrompt -Path $configFile -Section "App" -Key "AppName" -Prompt "App registration display name" -Default $appNameDefault
    $certFolder = Join-Path $scriptRoot "cert-output"; if (-not (Test-Path $certFolder)) { New-Item -ItemType Directory -Path $certFolder | Out-Null }
    $cfg = Get-IniContent -Path $configFile
    $clientId = $cfg["App"]["ClientId"]; $pfxPath = $cfg["App"]["PfxPath"]; $thumb = $cfg["App"]["Thumbprint"]
    $certPassword = $null

    if ($ForceRecreateApp -or -not $clientId -or -not $pfxPath -or -not (Test-Path $pfxPath)) {
        do {
            $pw1 = Read-Host -AsSecureString "Enter certificate password"
            $pw2 = Read-Host -AsSecureString "Confirm certificate password"
            $b1=[Runtime.InteropServices.Marshal]::SecureStringToBSTR($pw1); $b2=[Runtime.InteropServices.Marshal]::SecureStringToBSTR($pw2)
            $s1=[Runtime.InteropServices.Marshal]::PtrToStringBSTR($b1); $s2=[Runtime.InteropServices.Marshal]::PtrToStringBSTR($b2)
            [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($b1); [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($b2)
        } while (-not $s1 -or $s1 -ne $s2)
        $certPassword = $pw1

        $graphPerms=@("Group.ReadWrite.All","User.Read.All","Sites.ReadWrite.All")
        $spoPerms=@("Sites.FullControl.All")

        $reg = Register-PnPAzureADApp -ApplicationName $appName -Tenant $tenantId -Store CurrentUser -OutPath $certFolder -GraphApplicationPermissions $graphPerms -SharePointApplicationPermissions $spoPerms
        $clientId = $reg.'AzureAppId/ClientId'; if (-not $clientId) { $clientId = $reg.AzureAppId }
        Start-Sleep 45

        $storeCert = Get-ChildItem Cert:\CurrentUser\My | Where-Object { $_.Subject -like "*$appName*" -and $_.HasPrivateKey } | Sort-Object NotAfter -Descending | Select-Object -First 1
        if (-not $storeCert) { throw "Certificate not found for $appName" }

        $pfxPath = Join-Path $certFolder "$appName.pfx"
        Export-PfxCertificate -Cert $storeCert -FilePath $pfxPath -Password $certPassword -Force
        $thumb = $storeCert.Thumbprint

        Set-IniValue -Path $configFile -Section "App" -Key "ClientId" -Value $clientId
        Set-IniValue -Path $configFile -Section "App" -Key "PfxPath" -Value $pfxPath
        Set-IniValue -Path $configFile -Section "App" -Key "Thumbprint" -Value $thumb

        $consent = "https://login.microsoftonline.com/$tenantId/adminconsent?client_id=$clientId"
        Write-Host "Grant admin consent: $consent" -ForegroundColor Yellow
        try { Start-Process $consent | Out-Null } catch {}
        Read-Host "Press Enter after consent"
        Start-Sleep 45
    } else {
        $certPassword = Read-Host -AsSecureString "Enter the PFX certificate password"
    }

    # Connect Admin & ensure site
    Connect-PnPOnline -Url $adminUrl -ClientId $clientId -Tenant $tenantId -CertificatePath $pfxPath -CertificatePassword $certPassword
    $existingSite = Get-PnPTenantSite -Url $siteUrl -ErrorAction SilentlyContinue
    if (-not $existingSite) {
        if ([string]::IsNullOrWhiteSpace($ownerUpn)) {
            $ownerUpn = Read-Host "Owner UPN required to create site"
            while ([string]::IsNullOrWhiteSpace($ownerUpn)) { $ownerUpn = Read-Host "Owner UPN cannot be blank. Enter Site Owner UPN" }
            Set-IniValue -Path $configFile -Section "SharePoint" -Key "OwnerUpn" -Value $ownerUpn
        }
        New-PnPSite -Type TeamSite -Alias $siteAlias -Title $siteTitle -Owners $ownerUpn -IsPublic:$false | Out-Null
        for ($i=0;$i -lt 12;$i++){ Start-Sleep 10; $existingSite = Get-PnPTenantSite -Url $siteUrl -ErrorAction SilentlyContinue; if ($existingSite){break} }
        if (-not $existingSite) { throw "Site did not appear ready in time: $siteUrl" }
    } else { Write-Host "✓ Site already exists" -ForegroundColor Green }
    Disconnect-PnPOnline

    # Connect Site
    Connect-PnPOnline -Url $siteUrl -ClientId $clientId -Tenant $tenantId -CertificatePath $pfxPath -CertificatePassword $certPassword
    Write-Host "✓ Connected to site" -ForegroundColor Green

    # Apply regional settings (native or CSOM fallback)
    Apply-RegionalSettings -LocaleId $localeId -TimeZoneName $timeZoneName -FirstDayOfWeek $firstDay -Use24HourClock $use24hBool

    # Create lists & libraries
    Ensure-List -Title "Customers" -Template "GenericList" -EnableAttachments:$false -Url "Customers" -OnQuickLaunch
    Ensure-List -Title "Suppliers" -Template "GenericList" -EnableAttachments:$false -Url "Suppliers" -OnQuickLaunch
    Ensure-List -Title "Ledger"    -Template "GenericList" -EnableAttachments:$true -Url "Ledger" -OnQuickLaunch
    Ensure-List -Title "Invoices"  -Template "GenericList" -EnableAttachments:$true -Url "Invoices" -OnQuickLaunch
    Ensure-List -Title "Quotes"    -Template "GenericList" -EnableAttachments:$true -Url "Quotes" -OnQuickLaunch

    # =======================
    # Customers (updated fields)
    # =======================
    Ensure-Field -List "Customers" -DisplayName "Customer Name"    -InternalName "Title"           -Type Text -Indexed:$true -EnforceUnique:$true
    Ensure-Field -List "Customers" -DisplayName "Customer Code"    -InternalName "CustomerCode"    -Type Text -Required:$true -Indexed:$true -EnforceUnique:$true
    Ensure-Field -List "Customers" -DisplayName "Contact Name"     -InternalName "ContactName"     -Type Text
    Ensure-Field -List "Customers" -DisplayName "Email"            -InternalName "Email"           -Type Text
    Ensure-Field -List "Customers" -DisplayName "Billing Email"    -InternalName "BillingEmail"    -Type Text
    Ensure-Field -List "Customers" -DisplayName "Billing Address"  -InternalName "BillingAddress"  -Type Note
    Ensure-Field -List "Customers" -DisplayName "Default Day Rate" -InternalName "DefaultDayRate"  -Type Currency
    Ensure-Field -List "Customers" -DisplayName "Default Hourly Rate" -InternalName "DefaultHourlyRate" -Type Currency
    Ensure-Field -List "Customers" -DisplayName "Default VAT Rate" -InternalName "DefaultVATRate"  -Type Number
    Ensure-Field -List "Customers" -DisplayName "Is VAT Registered" -InternalName "IsVATRegistered" -Type Boolean
    Set-PnPField -List "Customers" -Identity "DefaultVATRate"     -Values @{ DefaultValue = "20" } | Out-Null
    Set-PnPField -List "Customers" -Identity "IsVATRegistered"    -Values @{ DefaultValue = "1" } | Out-Null
    Set-CurrencyOnField -List "Customers" -FieldInternalName "DefaultDayRate" -CurrencyLcid $currencyLcid
    Set-CurrencyOnField -List "Customers" -FieldInternalName "DefaultHourlyRate" -CurrencyLcid $currencyLcid

    # Customers view
    Ensure-View -List "Customers" -Title "All Customers" -Fields @(
        "Title","CustomerCode","BillingEmail","BillingAddress","DefaultDayRate","DefaultHourlyRate","ContactName","Email","IsVATRegistered","DefaultVATRate"
    )
    try {
        $v = Get-PnPView -List "Customers" -Identity "All Customers" -ErrorAction Stop
        Set-PnPView -List "Customers" -Identity $v.Id -Values @{ DefaultView = $true } | Out-Null
    } catch {
        Write-Warning ("Could not set default view on Customers: {0}" -f $_.Exception.Message)
    }

    # =======================
    # Payees (formerly Suppliers) - Comprehensive payee/supplier management
    # =======================
    # Rename list display name to "Payees" (keeps internal URL /Lists/Suppliers)
    try {
        $suppliersList = Get-PnPList -Identity "Suppliers" -ErrorAction Stop
        if ($suppliersList.Title -ne "Payees") {
            Set-PnPList -Identity "Suppliers" -Title "Payees" | Out-Null
            Write-Host "  ✓ Renamed 'Suppliers' list to 'Payees'" -ForegroundColor Green
        }
    } catch {
        Write-Warning "Could not rename Suppliers list: $($_.Exception.Message)"
    }

    # Core identity and classification
    Ensure-Field -List "Suppliers" -DisplayName "Payee Name"      -InternalName "Title"                 -Type Text -Indexed:$true -EnforceUnique:$true
    Ensure-Field -List "Suppliers" -DisplayName "Payee Code"      -InternalName "SupplierCode"          -Type Text -Required:$true -Indexed:$true -EnforceUnique:$true
    Ensure-Field -List "Suppliers" -DisplayName "Payee Type"      -InternalName "PayeeType"             -Type Choice -Choices @("Supplier","HMRC","Director","Payroll","Pension Provider","Utility","Landlord","Internal Ledger Account","Other")
    Ensure-Field -List "Suppliers" -DisplayName "Is Active"       -InternalName "IsActive"              -Type Boolean
    Set-PnPField -List "Suppliers" -Identity "IsActive" -Values @{ DefaultValue = "1" } -ErrorAction SilentlyContinue | Out-Null
    Ensure-Field -List "Suppliers" -DisplayName "On Hold"         -InternalName "OnHold"                -Type Boolean
    Set-PnPField -List "Suppliers" -Identity "OnHold" -Values @{ DefaultValue = "0" } -ErrorAction SilentlyContinue | Out-Null
    Ensure-Field -List "Suppliers" -DisplayName "Approval Required" -InternalName "ApprovalRequired"    -Type Boolean
    Set-PnPField -List "Suppliers" -Identity "ApprovalRequired" -Values @{ DefaultValue = "0" } -ErrorAction SilentlyContinue | Out-Null

    # Keep legacy field for backward compatibility
    Ensure-Field -List "Suppliers" -DisplayName "Category"         -InternalName "SupplierCategory" -Type Choice -Choices @("Equipment","Software","Cloud Services","Fuel","Travel","Insurance","Professional Fees","Other")

    # Contact & communications
    Ensure-Field -List "Suppliers" -DisplayName "Primary Contact"     -InternalName "PrimaryContact"        -Type Text
    Ensure-Field -List "Suppliers" -DisplayName "Email (Remittance)"  -InternalName "RemittanceEmail"       -Type Text
    Ensure-Field -List "Suppliers" -DisplayName "Statement Email"     -InternalName "StatementEmail"        -Type Text
    Ensure-Field -List "Suppliers" -DisplayName "Email"               -InternalName "SupplierEmail"         -Type Text
    Ensure-Field -List "Suppliers" -DisplayName "Phone"               -InternalName "Phone"                 -Type Text
    Ensure-Field -List "Suppliers" -DisplayName "Website"             -InternalName "Website"               -Type Text
    Ensure-Field -List "Suppliers" -DisplayName "Address"             -InternalName "Address"               -Type Note

    # Compliance & identifiers (UK-centric)
    Ensure-Field -List "Suppliers" -DisplayName "Companies House Number" -InternalName "CompaniesHouseNumber" -Type Text
    Ensure-Field -List "Suppliers" -DisplayName "VAT Registration"       -InternalName "VATRegistration"      -Type Text
    Ensure-Field -List "Suppliers" -DisplayName "UTR"                    -InternalName "UTR"                  -Type Text
    Ensure-Field -List "Suppliers" -DisplayName "CIS Status"             -InternalName "CISStatus"            -Type Choice -Choices @("Not Applicable","Registered","Gross","Net")
    Ensure-Field -List "Suppliers" -DisplayName "Insurance Expiry"       -InternalName "InsuranceExpiry"      -Type DateTime

    # Payment configuration
    Ensure-Field -List "Suppliers" -DisplayName "Preferred Payment Method" -InternalName "PaymentMethod" -Type Choice -Choices @("Bank Transfer","Direct Debit","Card","Other")
    Ensure-Field -List "Suppliers" -DisplayName "Payment Terms"            -InternalName "PaymentTerms"  -Type Choice -Choices @("Immediate","7 Days","14 Days","30 Days","60 Days","EOM+30")
    Ensure-Field -List "Suppliers" -DisplayName "Currency"                 -InternalName "Currency"      -Type Choice -Choices @("GBP","EUR","USD")
    Ensure-Field -List "Suppliers" -DisplayName "Default VAT Rate"         -InternalName "DefaultVATRate" -Type Number
    Ensure-Field -List "Suppliers" -DisplayName "Default Cost Centre"      -InternalName "DefaultCostCentre" -Type Text
    Ensure-Field -List "Suppliers" -DisplayName "Default Project"          -InternalName "DefaultProject"    -Type Text

    # Bank details
    Ensure-Field -List "Suppliers" -DisplayName "Bank Name"               -InternalName "BankName"             -Type Text
    Ensure-Field -List "Suppliers" -DisplayName "Account Name"            -InternalName "BankAccountName"      -Type Text
    Ensure-Field -List "Suppliers" -DisplayName "Sort Code"               -InternalName "SortCode"             -Type Text
    Ensure-Field -List "Suppliers" -DisplayName "Account Number"          -InternalName "AccountNumber"        -Type Text
    Ensure-Field -List "Suppliers" -DisplayName "Building Society Roll No" -InternalName "BuildingSocietyRollNumber" -Type Text
    Ensure-Field -List "Suppliers" -DisplayName "IBAN"                    -InternalName "IBAN"                 -Type Text
    Ensure-Field -List "Suppliers" -DisplayName "SWIFT/BIC"               -InternalName "SWIFTBIC"             -Type Text
    Ensure-Field -List "Suppliers" -DisplayName "Payment Reference Hint"  -InternalName "PaymentReferenceHint" -Type Text

    # Governance and integrations
    Ensure-Field -List "Suppliers" -DisplayName "Max Single Payment"      -InternalName "MaxPayment"           -Type Currency
    Set-CurrencyOnField -List "Suppliers" -FieldInternalName "MaxPayment" -CurrencyLcid $currencyLcid
    Ensure-Field -List "Suppliers" -DisplayName "External Vendor ID"      -InternalName "ExternalVendorId"     -Type Text
    Ensure-Field -List "Suppliers" -DisplayName "Notes"                   -InternalName "Notes"                -Type Note

    # Payees views
    Ensure-View -List "Suppliers" -Title "Active Suppliers" -Fields @(
        "Title","SupplierCode","PayeeType","PaymentTerms","DefaultVATRate","Currency","RemittanceEmail","Phone"
    ) -Query '<Where><And><Eq><FieldRef Name="PayeeType"/><Value Type="Choice">Supplier</Value></Eq><Eq><FieldRef Name="IsActive"/><Value Type="Integer">1</Value></Eq></And></Where>'
    
    Ensure-View -List "Suppliers" -Title "HMRC" -Fields @(
        "Title","PayeeType","PaymentReferenceHint","RemittanceEmail"
    ) -Query '<Where><And><Eq><FieldRef Name="PayeeType"/><Value Type="Choice">HMRC</Value></Eq><Eq><FieldRef Name="IsActive"/><Value Type="Integer">1</Value></Eq></And></Where>'
    
    Ensure-View -List "Suppliers" -Title "On Hold" -Fields @(
        "Title","SupplierCode","PayeeType","RemittanceEmail","Phone","OnHold"
    ) -Query '<Where><Eq><FieldRef Name="OnHold"/><Value Type="Integer">1</Value></Eq></Where>'
    
    Ensure-View -List "Suppliers" -Title "Missing Bank Details" -Fields @(
        "Title","SupplierCode","PaymentMethod","AccountNumber","SortCode","RemittanceEmail"
    ) -Query '<Where><And><Eq><FieldRef Name="PaymentMethod"/><Value Type="Choice">Bank Transfer</Value></Eq><Or><IsNull><FieldRef Name="AccountNumber"/></IsNull><IsNull><FieldRef Name="SortCode"/></IsNull></Or></And></Where>'
    
    Ensure-View -List "Suppliers" -Title "All Payees" -Fields @(
        "Title","SupplierCode","PayeeType","IsActive","RemittanceEmail","Phone","PaymentMethod","PaymentTerms"
    )

    # Set Active Suppliers as default view
    try {
        $activeView = Get-PnPView -List "Suppliers" -Identity "Active Suppliers" -ErrorAction Stop
        Set-PnPView -List "Suppliers" -Identity $activeView.Id -Values @{ DefaultView = $true } | Out-Null
    } catch {
        Write-Warning "Could not set default view on Suppliers: $($_.Exception.Message)"
    }

    # Enable versioning
    try {
        Set-PnPList -Identity "Suppliers" -EnableVersioning $true -MajorVersions 50 | Out-Null
        Write-Host "  ✓ Enabled versioning on Payees list" -ForegroundColor Green
    } catch {
        Write-Warning "Could not enable versioning: $($_.Exception.Message)"
    }

    # =======================
    # Expenses (renamed from Ledger for clarity)
    # =======================
    # Check if old "Ledger" list exists and migrate to "Expenses"
    $oldLedgerList = Get-PnPList -Identity "Ledger" -ErrorAction SilentlyContinue
    $expensesList = Get-PnPList -Identity "Expenses" -ErrorAction SilentlyContinue
    
    if ($oldLedgerList -and -not $expensesList) {
        Write-Host "  Migrating 'Ledger' list to 'Expenses'..." -ForegroundColor Cyan
        # Rename the list
        Set-PnPList -Identity "Ledger" -Title "Expenses"
        Write-Host "  ✓ Renamed 'Ledger' to 'Expenses'" -ForegroundColor Green
    }
    
    Ensure-List -Title "Expenses" -Template "GenericList" -EnableAttachments:$true -Url "Expenses" -OnQuickLaunch
    
    Ensure-Field -List "Expenses" -DisplayName "ID" -InternalName "Title" -Type Text
    Ensure-Field -List "Expenses" -DisplayName "Entry Type" -InternalName "EntryType" -Type Choice -Choices @("Expense") -Required:$true
    Ensure-Field -List "Expenses" -DisplayName "Entry Date" -InternalName "EntryDate" -Type DateTime -Required:$true
    Ensure-Field -List "Expenses" -DisplayName "Supplier"   -InternalName "Supplier"  -Type Lookup -LookupList "Suppliers" -LookupField "Title"
    Ensure-Field -List "Expenses" -DisplayName "Supplier Free Text" -InternalName "SupplierFreeText" -Type Text
    Ensure-Field -List "Expenses" -DisplayName "Category"           -InternalName "Category"        -Type Choice -Choices @("Equipment","Software","Cloud Services","Fuel","Travel","Insurance","Professional Fees","Other")

    # VAT controls
    Ensure-Field -List "Expenses" -DisplayName "VAT Applicability" -InternalName "VATApplicability" -Type Choice -Choices @("Standard","Reduced","Zero-rated","Exempt","Outside Scope")
    Ensure-Field -List "Expenses" -DisplayName "VAT Included"      -InternalName "VATIncluded"      -Type Boolean
    Set-PnPField -List "Expenses" -Identity "VATIncluded" -Values @{ DefaultValue = "1" } -ErrorAction SilentlyContinue | Out-Null
    Ensure-Field -List "Expenses" -DisplayName "VAT Rate"          -InternalName "VATRate"          -Type Number
    Set-PnPField -List "Expenses" -Identity "VATRate" -Values @{ DefaultValue = "20" } -ErrorAction SilentlyContinue | Out-Null

    Ensure-Field -List "Expenses" -DisplayName "Amount Net"   -InternalName "AmountNet"   -Type Currency
    Ensure-Field -List "Expenses" -DisplayName "VAT Amount"   -InternalName "VATAmount"   -Type Currency
    Ensure-Field -List "Expenses" -DisplayName "Amount Gross" -InternalName "AmountGross" -Type Currency

    Ensure-Field -List "Expenses" -DisplayName "Payment Method"    -InternalName "PaymentMethod"    -Type Choice -Choices @("Bank","Card","Cash","DLA","Other")
    Ensure-Field -List "Expenses" -DisplayName "Paid"              -InternalName "Paid"             -Type Boolean
    Ensure-Field -List "Expenses" -DisplayName "Date Paid"         -InternalName "DatePaid"         -Type DateTime
    Ensure-Field -List "Expenses" -DisplayName "Payment Reference" -InternalName "PaymentReference" -Type Text

    Ensure-Field -List "Expenses" -DisplayName "Tax Year"       -InternalName "TaxYear"       -Type Text
    Ensure-Field -List "Expenses" -DisplayName "Financial Year" -InternalName "FinancialYear" -Type Text
    Ensure-Field -List "Expenses" -DisplayName "DLA"            -InternalName "IsDLA"         -Type Boolean
    Ensure-Field -List "Expenses" -DisplayName "Related Document" -InternalName "RelatedDocument" -Type URL
    Ensure-Field -List "Expenses" -DisplayName "Notes"          -InternalName "Notes"         -Type Note

    # NeedsCalc (default Yes) so direct list edits get calculated by Flow
    Ensure-Field -List "Expenses" -DisplayName "Needs Calc" -InternalName "NeedsCalc" -Type Boolean
    Set-PnPField -List "Expenses" -Identity "NeedsCalc" -Values @{ DefaultValue = "1" } -ErrorAction SilentlyContinue | Out-Null

    # Clean up old Income entries from migrated Ledger (they're now in Invoices list)
    if ($oldLedgerList -and $expensesList) {
        Write-Host "  Cleaning up old Income entries from Expenses list..." -ForegroundColor Cyan
        $incomeEntries = Get-PnPListItem -List "Expenses" -Fields "EntryType" -PageSize 500 | Where-Object { $_["EntryType"] -eq "Income" }
        if ($incomeEntries) {
            $incomeEntries | ForEach-Object {
                Remove-PnPListItem -List "Expenses" -Identity $_.Id -Force
            }
            Write-Host "  ✓ Removed $($incomeEntries.Count) Income entries" -ForegroundColor Green
        }
    }

    # Views
    Ensure-View -List "Ledger" -Title "Income" -Fields @("Title","EntryDate","Customer","CustomerPORef","VATApplicability","AmountNet","VATAmount","AmountGross","Paid","RelatedDocument","TaxYear","FinancialYear") -Query '<Where><Eq><FieldRef Name="EntryType"/><Value Type="Choice">Income</Value></Eq></Where>'
    Ensure-View -List "Ledger" -Title "Expenses" -Fields @("Title","EntryDate","Supplier","VATApplicability","Category","AmountNet","VATAmount","AmountGross","Paid","RelatedDocument","TaxYear","FinancialYear") -Query '<Where><Eq><FieldRef Name="EntryType"/><Value Type="Choice">Expense</Value></Eq></Where>'
    Ensure-View -List "Ledger" -Title "Unpaid Invoices" -Fields @("Title","EntryDate","Customer","AmountGross","Paid","DatePaid","RelatedDocument") -Query '<Where><And><Eq><FieldRef Name="EntryType"/><Value Type="Choice">Income</Value></Eq><Eq><FieldRef Name="Paid"/><Value Type="Integer">0</Value></Eq></And></Where>'

    # =======================
    # Invoices (with discounts)
    # =======================
    Ensure-Field -List "Invoices" -DisplayName "Invoice Number" -InternalName "InvoiceNumber" -Type Text -Indexed:$true -EnforceUnique:$true
    Ensure-Field -List "Invoices" -DisplayName "Customer"       -InternalName "InvCustomer"   -Type Lookup -LookupList "Customers" -LookupField "Title"
    Ensure-Field -List "Invoices" -DisplayName "PO Reference"   -InternalName "POReference"   -Type Text
    Ensure-Field -List "Invoices" -DisplayName "Date Issued"    -InternalName "InvDateIssued" -Type DateTime
    Ensure-Field -List "Invoices" -DisplayName "Due Date"       -InternalName "DueDate"       -Type DateTime
    Ensure-Field -List "Invoices" -DisplayName "Date Paid"      -InternalName "InvDatePaid"   -Type DateTime
    Ensure-Field -List "Invoices" -DisplayName "Status"         -InternalName "InvStatus"     -Type Choice -Choices @("Draft","Issued","Paid","Overdue")
    Ensure-Field -List "Invoices" -DisplayName "Amount Net"     -InternalName "InvAmountNet"  -Type Currency
    Ensure-Field -List "Invoices" -DisplayName "Discount Percent" -InternalName "DiscountPercent" -Type Number
    Ensure-Field -List "Invoices" -DisplayName "Discount Amount"  -InternalName "DiscountAmount"  -Type Currency
    Ensure-Field -List "Invoices" -DisplayName "Discount Note"    -InternalName "DiscountNote"    -Type Note
    Ensure-Field -List "Invoices" -DisplayName "VAT Amount"     -InternalName "InvVATAmount"  -Type Currency
    Ensure-Field -List "Invoices" -DisplayName "Amount Gross"   -InternalName "InvAmountGross" -Type Currency
    Ensure-Field -List "Invoices" -DisplayName "Tax Year"       -InternalName "TaxYear"       -Type Text
    Ensure-Field -List "Invoices" -DisplayName "Financial Year" -InternalName "FinancialYear" -Type Text
    Ensure-Field -List "Invoices" -DisplayName "Line Items JSON" -InternalName "LineItemsJSON" -Type Note

    Ensure-View -List "Invoices" -Title "All Invoices" -Fields @(
        "FileLeafRef","InvoiceNumber","InvCustomer","POReference","InvDateIssued","InvStatus",
        "InvAmountNet","DiscountPercent","DiscountAmount","DiscountNote",
        "InvVATAmount","InvAmountGross","TaxYear","FinancialYear"
    )

    Set-CurrencyOnField -List "Invoices" -FieldInternalName "InvAmountNet" -CurrencyLcid $currencyLcid
    Set-CurrencyOnField -List "Invoices" -FieldInternalName "DiscountAmount" -CurrencyLcid $currencyLcid
    Set-CurrencyOnField -List "Invoices" -FieldInternalName "InvVATAmount" -CurrencyLcid $currencyLcid
    Set-CurrencyOnField -List "Invoices" -FieldInternalName "InvAmountGross" -CurrencyLcid $currencyLcid

    # =======================
    # Quotes (NEW)
    # =======================
    Ensure-Field -List "Quotes" -DisplayName "Quote Number"      -InternalName "QuoteNumber"        -Type Text -Required:$true -Indexed:$true -EnforceUnique:$true
    Ensure-Field -List "Quotes" -DisplayName "Customer"          -InternalName "QuoteCustomer"      -Type Lookup -LookupList "Customers" -LookupField "Title"
    Ensure-Field -List "Quotes" -DisplayName "Date Issued"       -InternalName "QuoteDateIssued"    -Type DateTime
    Ensure-Field -List "Quotes" -DisplayName "Status"            -InternalName "QuoteStatus"        -Type Choice -Choices @("Draft","Sent","Accepted","Declined","Expired","ConvertedToInvoice")
    Ensure-Field -List "Quotes" -DisplayName "Valid Until"       -InternalName "QuoteValidUntil"    -Type DateTime
    Ensure-Field -List "Quotes" -DisplayName "Amount Net"        -InternalName "QuoteAmountNet"     -Type Currency
    Ensure-Field -List "Quotes" -DisplayName "Discount Percent"  -InternalName "QuoteDiscountPercent" -Type Number
    Ensure-Field -List "Quotes" -DisplayName "Discount Amount"   -InternalName "QuoteDiscountAmount"  -Type Currency
    Ensure-Field -List "Quotes" -DisplayName "Discount Note"     -InternalName "QuoteDiscountNote"    -Type Note
    Ensure-Field -List "Quotes" -DisplayName "VAT Amount"        -InternalName "QuoteVATAmount"       -Type Currency
    Ensure-Field -List "Quotes" -DisplayName "Overall Amount"    -InternalName "QuoteAmountGross"     -Type Currency
    Ensure-Field -List "Quotes" -DisplayName "Tax Year"          -InternalName "TaxYear"              -Type Text
    Ensure-Field -List "Quotes" -DisplayName "Financial Year"    -InternalName "FinancialYear"        -Type Text
    Ensure-Field -List "Quotes" -DisplayName "Line Items JSON"   -InternalName "LineItemsJSON"        -Type Note
    Ensure-Field -List "Quotes" -DisplayName "Linked Invoice ID" -InternalName "LinkedInvoiceId"      -Type Lookup -LookupList "Invoices" -LookupField "InvoiceNumber"

    Ensure-View -List "Quotes" -Title "All Quotes" -Fields @(
        "QuoteNumber","QuoteCustomer","QuoteDateIssued","QuoteStatus","QuoteValidUntil",
        "QuoteAmountNet","QuoteDiscountPercent","QuoteDiscountAmount","QuoteVATAmount","QuoteAmountGross",
        "LinkedInvoiceId"
    )

    Set-CurrencyOnField -List "Quotes" -FieldInternalName "QuoteAmountNet" -CurrencyLcid $currencyLcid
    Set-CurrencyOnField -List "Quotes" -FieldInternalName "QuoteDiscountAmount" -CurrencyLcid $currencyLcid
    Set-CurrencyOnField -List "Quotes" -FieldInternalName "QuoteVATAmount" -CurrencyLcid $currencyLcid
    Set-CurrencyOnField -List "Quotes" -FieldInternalName "QuoteAmountGross" -CurrencyLcid $currencyLcid

    # =======================
    # Share Classes (for Shareholders)
    # =======================
    Ensure-List -Title "ShareClasses" -Template "GenericList" -EnableAttachments:$false -Url "ShareClasses" -OnQuickLaunch

    Ensure-Field -List "ShareClasses" -DisplayName "Share Class Code"      -InternalName "Title"               -Type Text -Required:$true -Indexed:$true
    Ensure-Field -List "ShareClasses" -DisplayName "Display Name"          -InternalName "DisplayName"         -Type Text
    Ensure-Field -List "ShareClasses" -DisplayName "Voting Rights"         -InternalName "VotingRights"        -Type Choice -Choices @("Full","Limited","None")
    Ensure-Field -List "ShareClasses" -DisplayName "Dividend Policy Note"  -InternalName "DividendPolicyNote"  -Type Note
    Ensure-Field -List "ShareClasses" -DisplayName "Is Active"             -InternalName "IsActive"            -Type Boolean
    Ensure-Field -List "ShareClasses" -DisplayName "Notes"                 -InternalName "Notes"               -Type Note

    Ensure-View -List "ShareClasses" -Title "All Share Classes" -Fields @(
        "Title","DisplayName","VotingRights","DividendPolicyNote","IsActive"
    )

    Ensure-View -List "ShareClasses" -Title "Active Share Classes" -Fields @(
        "Title","DisplayName","VotingRights","IsActive"
    ) -Filter "IsActive eq 1"

    # Seed default share classes
    Write-Host "  Seeding default share classes..." -ForegroundColor Yellow
    $shareClasses = @(
        @{
            Title = "A"
            DisplayName = "A Ordinary Shares"
            VotingRights = "Full"
            DividendPolicyNote = "Dividends may be declared independently for A class"
            IsActive = $true
            Notes = ""
        },
        @{
            Title = "B"
            DisplayName = "B Ordinary Shares"
            VotingRights = "Limited"
            DividendPolicyNote = "Dividends may be declared independently for B class"
            IsActive = $true
            Notes = ""
        }
    )

    foreach ($sc in $shareClasses) {
        $existingItem = Get-PnPListItem -List "ShareClasses" -Query "<View><Query><Where><Eq><FieldRef Name='Title'/><Value Type='Text'>$($sc.Title)</Value></Eq></Where></Query></View>" -ErrorAction SilentlyContinue
        if (-not $existingItem) {
            Add-PnPListItem -List "ShareClasses" -Values @{
                "Title" = $sc.Title
                "DisplayName" = $sc.DisplayName
                "VotingRights" = $sc.VotingRights
                "DividendPolicyNote" = $sc.DividendPolicyNote
                "IsActive" = $sc.IsActive
                "Notes" = $sc.Notes
            } | Out-Null
            Write-Host "    Created share class: $($sc.Title)" -ForegroundColor Green
        }
    }

    # =======================
    # Shareholders (NEW)
    # =======================
    Ensure-List -Title "Shareholders" -Template "GenericList" -EnableAttachments:$true -Url "Shareholders" -OnQuickLaunch

    Ensure-Field -List "Shareholders" -DisplayName "Shareholder Name"     -InternalName "Title"                   -Type Text -Required:$true -Indexed:$true
    Ensure-Field -List "Shareholders" -DisplayName "Shareholder Type"    -InternalName "ShareholderType"        -Type Choice -Choices @("Individual","Corporate")
    Ensure-Field -List "Shareholders" -DisplayName "Share Class"         -InternalName "ShareClass"             -Type Lookup -LookupList "ShareClasses" -LookupField "Title"
    Ensure-Field -List "Shareholders" -DisplayName "Is Active"           -InternalName "IsActive"               -Type Boolean
    Ensure-Field -List "Shareholders" -DisplayName "Shares Owned"        -InternalName "SharesOwned"            -Type Number
    Ensure-Field -List "Shareholders" -DisplayName "Share Certificate No" -InternalName "ShareCertificateNumber" -Type Text
    Ensure-Field -List "Shareholders" -DisplayName "Date of Issue"       -InternalName "DateOfIssue"            -Type DateTime
    Ensure-Field -List "Shareholders" -DisplayName "Email"               -InternalName "Email"                  -Type Text
    Ensure-Field -List "Shareholders" -DisplayName "Address"             -InternalName "Address"                -Type Note
    Ensure-Field -List "Shareholders" -DisplayName "Notes"               -InternalName "Notes"                  -Type Note

    Ensure-View -List "Shareholders" -Title "Active Shareholders" -Fields @(
        "Title","ShareClass","SharesOwned","ShareCertificateNumber","Email","DateOfIssue","IsActive"
    ) -Filter "IsActive eq 1"

    Ensure-View -List "Shareholders" -Title "By Share Class" -Fields @(
        "Title","SharesOwned","ShareCertificateNumber","IsActive","Email"
    ) -GroupBy "ShareClass"

    Ensure-View -List "Shareholders" -Title "All Shareholders" -Fields @(
        "Title","ShareholderType","ShareClass","SharesOwned","ShareCertificateNumber","DateOfIssue","Email","IsActive"
    )

    # =======================
    # Employees (NEW - for payroll tracking)
    # =======================
    Ensure-List -Title "Employees" -Template "GenericList" -EnableAttachments:$true -Url "Employees" -OnQuickLaunch

    Ensure-Field -List "Employees" -DisplayName "Employee Name"           -InternalName "Title"                      -Type Text -Required:$true -Indexed:$true
    Ensure-Field -List "Employees" -DisplayName "Employee Number"         -InternalName "EmployeeNumber"             -Type Text -Indexed:$true
    Ensure-Field -List "Employees" -DisplayName "Email"                   -InternalName "Email"                      -Type Text
    Ensure-Field -List "Employees" -DisplayName "National Insurance No"   -InternalName "NationalInsuranceNumber"    -Type Text
    Ensure-Field -List "Employees" -DisplayName "Tax Code"                -InternalName "TaxCode"                    -Type Text
    Ensure-Field -List "Employees" -DisplayName "Annual Salary"           -InternalName "AnnualSalary"               -Type Number
    Ensure-Field -List "Employees" -DisplayName "Payment Schedule"        -InternalName "PaymentSchedule"            -Type Choice -Choices @("Monthly","Weekly","Bi-weekly")
    Ensure-Field -List "Employees" -DisplayName "Start Date"              -InternalName "StartDate"                  -Type DateTime
    Ensure-Field -List "Employees" -DisplayName "Bank Account Name"       -InternalName "BankAccountName"            -Type Text
    Ensure-Field -List "Employees" -DisplayName "Bank Account Number"     -InternalName "BankAccountNumber"          -Type Text
    Ensure-Field -List "Employees" -DisplayName "Bank Sort Code"          -InternalName "BankSortCode"               -Type Text
    Ensure-Field -List "Employees" -DisplayName "Address"                 -InternalName "Address"                    -Type Note
    Ensure-Field -List "Employees" -DisplayName "Phone Number"            -InternalName "PhoneNumber"                -Type Text
    Ensure-Field -List "Employees" -DisplayName "Is Active"               -InternalName "IsActive"                   -Type Boolean
    Ensure-Field -List "Employees" -DisplayName "Notes"                   -InternalName "Notes"                      -Type Note

    Ensure-View -List "Employees" -Title "Active Employees" -Fields @(
        "Title","EmployeeNumber","Email","TaxCode","AnnualSalary","PaymentSchedule","StartDate","IsActive"
    ) -Filter "IsActive eq 1"

    Ensure-View -List "Employees" -Title "All Employees" -Fields @(
        "Title","EmployeeNumber","Email","NationalInsuranceNumber","TaxCode","AnnualSalary","PaymentSchedule","StartDate","IsActive"
    )

    # =======================
    # Company Ledger (non-trading entries: salary, NI, PAYE, DLA, corporation tax, dividends)
    # =======================
    Ensure-List -Title "CompanyLedger" -Template "GenericList" -EnableAttachments:$false -Url "CompanyLedger" -OnQuickLaunch

    Ensure-Field -List "CompanyLedger" -DisplayName "Entry Title"    -InternalName "Title"            -Type Text
    Ensure-Field -List "CompanyLedger" -DisplayName "Entry Type"     -InternalName "CompanyEntryType" -Type Choice -Choices @("Salary","EmployeeNI","EmployerNI","PAYE","DLA_In","DLA_Out","CorpTax_Reserve","CorpTax_Paid","Dividend_Declared","Dividend_Paid") -Required:$true
    Ensure-Field -List "CompanyLedger" -DisplayName "Amount"         -InternalName "Amount"           -Type Currency -Required:$true
    Ensure-Field -List "CompanyLedger" -DisplayName "Effective Date" -InternalName "EffectiveDate"    -Type DateTime -Required:$true
    Ensure-Field -List "CompanyLedger" -DisplayName "Notes"          -InternalName "Notes"            -Type Note
    Ensure-Field -List "CompanyLedger" -DisplayName "Period Key"     -InternalName "PeriodKey"        -Type Text
    Ensure-Field -List "CompanyLedger" -DisplayName "Tax Year"       -InternalName "TaxYear"          -Type Text
    Ensure-Field -List "CompanyLedger" -DisplayName "Financial Year" -InternalName "FinancialYear"    -Type Text

    Set-CurrencyOnField -List "CompanyLedger" -FieldInternalName "Amount" -CurrencyLcid $currencyLcid

    Ensure-View -List "CompanyLedger" -Title "All Company Entries" -Fields @(
        "Title","CompanyEntryType","Amount","EffectiveDate","PeriodKey","TaxYear","FinancialYear","Notes"
    )

    # =======================
    # Company Documents Library
    # =======================
    Ensure-List -Title "Company Documents" -Template "DocumentLibrary" -Url "CompanyDocuments" -OnQuickLaunch
    
    # Comprehensive document type choices covering all use cases
    Ensure-Field -List "Company Documents" -DisplayName "Document Type" -InternalName "DocumentType" -Type Choice -Choices @(
        "Company Logo",
        "Director Signature",
        "Officer Signature",
        "Share Certificate",
        "Template",
        "Meeting Minutes",
        "Articles of Association",
        "Financial Statement",
        "Contract",
        "Policy",
        "Tax Return",
        "Correspondence",
        "Legal Document",
        "Other"
    )
    
    # Metadata fields for flexible document management
    Ensure-Field -List "Company Documents" -DisplayName "Person Name"    -InternalName "PersonName"    -Type Text
    Ensure-Field -List "Company Documents" -DisplayName "Person Title"   -InternalName "PersonTitle"   -Type Text
    Ensure-Field -List "Company Documents" -DisplayName "Is Active"      -InternalName "IsActive"      -Type Boolean
    Ensure-Field -List "Company Documents" -DisplayName "Related Entity" -InternalName "RelatedEntity" -Type Text
    Ensure-Field -List "Company Documents" -DisplayName "Document Date"  -InternalName "DocumentDate"  -Type DateTime
    Ensure-Field -List "Company Documents" -DisplayName "Expiry Date"    -InternalName "ExpiryDate"    -Type DateTime
    Ensure-Field -List "Company Documents" -DisplayName "Notes"          -InternalName "DocNotes"      -Type Note

    # Default view showing all key fields
    Ensure-View -List "Company Documents" -Title "All Company Documents" -Fields @(
        "FileLeafRef","DocumentType","PersonName","PersonTitle","IsActive","RelatedEntity","DocumentDate","DocNotes","Modified"
    )

    # =======================
    # Company Settings (seeded)
    # =======================
    Ensure-List -Title "Company Settings" -Template "GenericList" -EnableAttachments:$false -Url "CompanySettings" -OnQuickLaunch

    # Identity & contact
    Ensure-Field -List "Company Settings" -DisplayName "Profile Name"       -InternalName "Title"                 -Type Text -Indexed:$true -EnforceUnique:$true
    Ensure-Field -List "Company Settings" -DisplayName "Business Name"      -InternalName "BusinessName"          -Type Text
    Ensure-Field -List "Company Settings" -DisplayName "Trading Name"       -InternalName "TradingName"           -Type Text
    Ensure-Field -List "Company Settings" -DisplayName "Contact Name"       -InternalName "ContactName"           -Type Text
    Ensure-Field -List "Company Settings" -DisplayName "Invoicing Email"    -InternalName "InvoicingEmail"        -Type Text
    Ensure-Field -List "Company Settings" -DisplayName "Invoicing Phone"    -InternalName "InvoicingPhone"        -Type Text
    Ensure-Field -List "Company Settings" -DisplayName "Registered Address" -InternalName "RegisteredAddress"     -Type Note
    Ensure-Field -List "Company Settings" -DisplayName "Invoices Mailbox"   -InternalName "InvoicesEmail"         -Type Text
    Ensure-Field -List "Company Settings" -DisplayName "Quotes Mailbox"     -InternalName "QuotesEmail"           -Type Text
    Ensure-Field -List "Company Settings" -DisplayName "Payments Mailbox"   -InternalName "PaymentsEmail"         -Type Text

    # Registration & tax
    Ensure-Field -List "Company Settings" -DisplayName "Company Reg No"     -InternalName "CompanyRegNo"          -Type Text
    Ensure-Field -List "Company Settings" -DisplayName "VAT Reg No"         -InternalName "VATRegNo"              -Type Text
    Ensure-Field -List "Company Settings" -DisplayName "Default VAT Rate"   -InternalName "DefaultVATRate"        -Type Number
    Ensure-Field -List "Company Settings" -DisplayName "Base Currency"      -InternalName "BaseCurrency"          -Type Text
    Ensure-Field -List "Company Settings" -DisplayName "Currency Symbol"    -InternalName "CurrencySymbol"        -Type Text

    # FY boundary
    Ensure-Field -List "Company Settings" -DisplayName "Company Inception Date" -InternalName "CompanyInceptionDate" -Type DateTime
    Ensure-Field -List "Company Settings" -DisplayName "FY Start Month"     -InternalName "FYStartMonth"          -Type Number
    Ensure-Field -List "Company Settings" -DisplayName "FY Start Day"       -InternalName "FYStartDay"            -Type Number

    # Invoice numbering & payment terms
    Ensure-Field -List "Company Settings" -DisplayName "Invoice Prefix"     -InternalName "InvoicePrefix"         -Type Text
    Ensure-Field -List "Company Settings" -DisplayName "Quote Prefix"       -InternalName "QuotePrefix"           -Type Text
    Ensure-Field -List "Company Settings" -DisplayName "Next Invoice No"    -InternalName "NextInvoiceNo"         -Type Number
    Ensure-Field -List "Company Settings" -DisplayName "Payment Terms (days)" -InternalName "PaymentTermsDays"    -Type Number
    Ensure-Field -List "Company Settings" -DisplayName "Invoice Footer Text" -InternalName "InvoiceFooterText"    -Type Note
    Ensure-Field -List "Company Settings" -DisplayName "Company Logo URL"   -InternalName "LogoUrl"               -Type URL

    # Bank details (optional)
    Ensure-Field -List "Company Settings" -DisplayName "Bank Account Name"  -InternalName "BankAccountName"       -Type Text
    Ensure-Field -List "Company Settings" -DisplayName "Sort Code"          -InternalName "BankSortCode"          -Type Text
    Ensure-Field -List "Company Settings" -DisplayName "Account Number"     -InternalName "BankAccountNumber"     -Type Text
    Ensure-Field -List "Company Settings" -DisplayName "IBAN"               -InternalName "BankIBAN"              -Type Text
    Ensure-Field -List "Company Settings" -DisplayName "SWIFT/BIC"          -InternalName "BankSWIFT"             -Type Text

    # SMTP Settings (for SMTP2Go email)
    Ensure-Field -List "Company Settings" -DisplayName "SMTP Server"         -InternalName "SmtpServer"            -Type Text
    Ensure-Field -List "Company Settings" -DisplayName "SMTP Port"           -InternalName "SmtpPort"              -Type Number
    Ensure-Field -List "Company Settings" -DisplayName "SMTP From Address"   -InternalName "SmtpFromAddress"       -Type Text
    Ensure-Field -List "Company Settings" -DisplayName "SMTP Username"       -InternalName "SmtpUsername"          -Type Text

    # Director information
    Ensure-Field -List "Company Settings" -DisplayName "Director Name"       -InternalName "DirectorName"          -Type Text
    Ensure-Field -List "Company Settings" -DisplayName "Director Signature"  -InternalName "DirectorSignature"     -Type Note
    Ensure-Field -List "Company Settings" -DisplayName "Has Authorized Officer" -InternalName "HasAuthorizedOfficer" -Type Boolean
    Ensure-Field -List "Company Settings" -DisplayName "Authorized Officer"  -InternalName "AuthorizedOfficerName" -Type Text
    Ensure-Field -List "Company Settings" -DisplayName "Officer Signature"   -InternalName "AuthorizedOfficerSignature" -Type Note

    # Seed a single default item if none exists
    try {
        $existingCompanyItem = Get-PnPListItem -List "Company Settings" -PageSize 1 | Select-Object -First 1
        if (-not $existingCompanyItem) {
            Add-PnPListItem -List "Company Settings" -Values @{
                Title            = "Default"
                BusinessName     = "Your Business Ltd"
                BaseCurrency     = $baseCurrencyCode
                DefaultVATRate   = 20
                FYStartMonth     = 1
                FYStartDay       = 1
                PaymentTermsDays = 14
                SmtpServer       = "mail.smtp2go.com"
                SmtpPort         = 587
            } | Out-Null
            Write-Host "✓ Seeded Company Settings (Profile: Default)" -ForegroundColor Green
        }
    } catch {
        Write-Warning ("Could not seed Company Settings: {0}" -f $_.Exception.Message)
    }

    # Apply currency LCID to all Currency fields (Ledger)
    Set-CurrencyOnField -List "Ledger" -FieldInternalName "AmountNet" -CurrencyLcid $currencyLcid
    Set-CurrencyOnField -List "Ledger" -FieldInternalName "VATAmount" -CurrencyLcid $currencyLcid
    Set-CurrencyOnField -List "Ledger" -FieldInternalName "AmountGross" -CurrencyLcid $currencyLcid

    # =======================
    # Azure Key Vault Setup (for SMTP password)
    # =======================
    Write-Host "`n=== Azure Key Vault Setup ===" -ForegroundColor Cyan
    
    $createKeyVault = Read-Host "Do you want to create/configure Azure Key Vault for SMTP password? (Y/N)"
    if ($createKeyVault -eq "Y" -or $createKeyVault -eq "y") {
        try {
            # Check if Azure CLI is installed
            $azInstalled = Get-Command az -ErrorAction SilentlyContinue
            if (-not $azInstalled) {
                Write-Warning "Azure CLI (az) not found. Please install it from: https://aka.ms/installazurecliwindows"
                Write-Host "Skipping Key Vault setup..." -ForegroundColor Yellow
            } else {
                # Get or prompt for Key Vault details
                $resourceGroup = Get-IniValueOrPrompt -Path $configFile -Section "Azure" -Key "ResourceGroup" -Prompt "Azure Resource Group name" -Default "rg-financehub-prod"
                $keyVaultName = Get-IniValueOrPrompt -Path $configFile -Section "Azure" -Key "KeyVaultName" -Prompt "Key Vault name (must be globally unique)" -Default "kv-financehub-$tenantShort"
                $location = Get-IniValueOrPrompt -Path $configFile -Section "Azure" -Key "Location" -Prompt "Azure location" -Default "uksouth"
                $functionAppName = Get-IniValueOrPrompt -Path $configFile -Section "Azure" -Key "FunctionAppName" -Prompt "Function App name" -Default "func-financehub-2669"

                Write-Host "Checking if logged into Azure..." -ForegroundColor Yellow
                $account = az account show 2>$null | ConvertFrom-Json
                if (-not $account) {
                    Write-Host "Logging into Azure..." -ForegroundColor Yellow
                    az login
                }

                # Check if Resource Group exists
                $rgExists = az group exists --name $resourceGroup | ConvertFrom-Json
                if (-not $rgExists) {
                    Write-Host "Creating Resource Group: $resourceGroup" -ForegroundColor Yellow
                    az group create --name $resourceGroup --location $location | Out-Null
                    Write-Host "✓ Resource Group created" -ForegroundColor Green
                } else {
                    Write-Host "✓ Resource Group exists" -ForegroundColor Green
                }

                # Check if Key Vault exists
                $kvExists = az keyvault list --resource-group $resourceGroup --query "[?name=='$keyVaultName'].name" -o tsv
                if (-not $kvExists) {
                    Write-Host "Creating Key Vault: $keyVaultName" -ForegroundColor Yellow
                    az keyvault create --name $keyVaultName --resource-group $resourceGroup --location $location --enable-rbac-authorization false | Out-Null
                    Write-Host "✓ Key Vault created" -ForegroundColor Green
                } else {
                    Write-Host "✓ Key Vault exists" -ForegroundColor Green
                }

                # Prompt for SMTP password
                Write-Host "`nSMTP2Go Configuration:" -ForegroundColor Cyan
                $smtpPassword = Read-Host "Enter SMTP2Go password (or press Enter to skip)" -AsSecureString
                $smtpPasswordPlain = [Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime.InteropServices.Marshal]::SecureStringToBSTR($smtpPassword))
                
                if (-not [string]::IsNullOrWhiteSpace($smtpPasswordPlain)) {
                    Write-Host "Setting SMTP password in Key Vault..." -ForegroundColor Yellow
                    az keyvault secret set --vault-name $keyVaultName --name "SmtpPassword" --value $smtpPasswordPlain | Out-Null
                    Write-Host "✓ SMTP password stored in Key Vault" -ForegroundColor Green
                    
                    # Clear sensitive variable
                    $smtpPasswordPlain = $null
                }

                # Grant Function App access to Key Vault
                Write-Host "Granting Function App access to Key Vault..." -ForegroundColor Yellow
                
                # Get Function App principal ID
                $principalId = az functionapp identity show --name $functionAppName --resource-group $resourceGroup --query principalId -o tsv 2>$null
                
                if ($principalId) {
                    az keyvault set-policy --name $keyVaultName --object-id $principalId --secret-permissions get list | Out-Null
                    Write-Host "✓ Function App has access to Key Vault secrets" -ForegroundColor Green
                } else {
                    Write-Warning "Function App not found or doesn't have Managed Identity enabled."
                    Write-Host "Please enable Managed Identity on your Function App and run:" -ForegroundColor Yellow
                    Write-Host "  az keyvault set-policy --name $keyVaultName --object-id <principal-id> --secret-permissions get list" -ForegroundColor Yellow
                }

                # Store Key Vault URL in config
                $keyVaultUrl = "https://$keyVaultName.vault.azure.net/"
                Set-IniValue -Path $configFile -Section "Azure" -Key "KeyVaultUrl" -Value $keyVaultUrl

                Write-Host "`n✓ Key Vault setup complete" -ForegroundColor Green
                Write-Host "Key Vault URL: $keyVaultUrl" -ForegroundColor Cyan
            }
        } catch {
            Write-Warning "Key Vault setup failed: $($_.Exception.Message)"
            Write-Host "You can manually create the Key Vault and secret later." -ForegroundColor Yellow
        }
    } else {
        Write-Host "Skipping Key Vault setup. You can configure it later using Azure Portal or CLI." -ForegroundColor Yellow
    }

    Write-Host "`n✓ FinanceHub/QuoteHub SharePoint Provisioning Complete" -ForegroundColor Green
    Write-Host "Site URL: $siteUrl"
    Write-Host "Regional: LocaleId=$localeId, TimeZone='$timeZoneName', FirstDay=$firstDay, 24h=$use24hBool"
    Write-Host "Currency: $baseCurrencyCode (LCID $currencyLcid)"
    Write-Host "Config: $configFile"
    Write-Host "`nNew features:"
    Write-Host "  - Quotes List + Quote linkage to Invoices"
    Write-Host "  - CompanyLedger List for non-trading entries (salary, NI, PAYE, DLA, corporation tax, dividends)"
    Write-Host "  - Company Documents Library for key company documents"
    Write-Host "  - Customer/Supplier Codes (auto-generated by your app)"
    Write-Host "  - Customer Hourly Rate, Billing Address, VAT Registered flag"
    Write-Host "  - Invoice & Quote Discount fields (Percent, Amount, Note)"
    Write-Host "  - All currency fields configured with $baseCurrencyCode"

    Disconnect-PnPOnline | Out-Null
    exit 0
}
catch {
    Write-Host "`nERROR: $($_.Exception.Message)" -ForegroundColor Red
    Write-Host $_.ScriptStackTrace -ForegroundColor Red
    try { Disconnect-PnPOnline | Out-Null } catch {}
    exit 1
}